version: '3'
services:
  # weblogic:
  #   image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-11-230718
  #   ports:
  #     - 7001:7001
  #     - 9002:9002
  #   volumes:
  #     - $PWD:/u01/oracle/properties
  #   environment:
  #     - ADMINISTRATION_PORT_ENABLED=false

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
  
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200"
      - "4317"
    volumes:
      - $PWD/observability-config/tempo-config.yaml:/etc/tempo.yml
  
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - $PWD/observability-config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
        - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - loki
      - tempo
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - $PWD/observability-config/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      # - "1888:1888" # pprof extension
      # - "8888:8888" # Prometheus metrics exposed by the collector
      # - "8889:8889" # Prometheus exporter metrics
      # - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      # - "55679:55679" # zpages extension
    depends_on:
      - loki
      - tempo